<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-Q37MKND" name="com.bitnei.apitest.testcases.saas.GetInsurance" tests="4" failures="1" timestamp="08 七月 2020 08:30:24 GMT" time="1.145" errors="0">
  <testcase name="Insurance" time="0.038" classname="com.bitnei.apitest.testcases.saas.GetInsurance"/>
  <testcase name="Insurance" time="1.009" classname="com.bitnei.apitest.testcases.saas.GetInsurance"/>
  <testcase name="Insurance" time="0.059" classname="com.bitnei.apitest.testcases.saas.GetInsurance"/>
  <testcase name="Insurance" time="0.039" classname="com.bitnei.apitest.testcases.saas.GetInsurance">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;errorMsg&quot;:{&quot;currentValue is &quot;:&quot;参数vin、licensePlate至少传一个&quot;,&quot;expectedValue is &quot;:&quot;参数vin、licensePlate至少传一个！&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"errorMsg":{"currentValue is ":"参数vin、licensePlate至少传一个","expectedValue is ":"参数vin、licensePlate至少传一个！"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.GetInsurance.Insurance(GetInsurance.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Insurance -->
</testsuite> <!-- com.bitnei.apitest.testcases.saas.GetInsurance -->
