<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-Q37MKND" name="com.bitnei.apitest.testcases.saas.UserInforRgisterByExcel" tests="1" failures="1" timestamp="24 十月 2019 05:38:40 GMT" time="0.060" errors="0">
  <testcase name="UserInfoRgisterData" time="0.060" classname="com.bitnei.apitest.testcases.saas.UserInforRgisterByExcel">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;errorMsg&quot;:{&quot;currentValue is &quot;:&quot;str:用户hangang@bitnei.cn已经存在&quot;,&quot;expectedValue is &quot;:&quot;NORMAL&quot;},&quot;data&quot;:{&quot;currentValue is &quot;:null,&quot;expectedValue is &quot;:&quot;用户hangang@bitnei.cn已经存在&quot;,&quot;actualValue&quot;:null,&quot;expectedValue&quot;:&quot;用户hangang@bitnei.cn已经存在&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"errorMsg":{"currentValue is ":"str:用户hangang@bitnei.cn已经存在","expectedValue is ":"NORMAL"},"data":{"currentValue is ":null,"expectedValue is ":"用户hangang@bitnei.cn已经存在","actualValue":null,"expectedValue":"用户hangang@bitnei.cn已经存在"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.UserInforRgisterByExcel.UserInfoRgisterData(UserInforRgisterByExcel.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- UserInfoRgisterData -->
</testsuite> <!-- com.bitnei.apitest.testcases.saas.UserInforRgisterByExcel -->
